[package]
name = "runs_comparison"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
rand = "0.8"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "benchmark"
harness = false
